services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      NODE_EXTRA_CA_CERTS: /extra-ca/ThawteTLSRSACAG1.crt
    volumes:
      - ./extra-ca:/extra-ca:ro
      - ./data:/app/data
    ports:
      - ${HOST}:${PORT}:3001
