services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: ["bash", "/custom-scripts/start.sh"]
    volumes:
      - ./scripts:/custom-scripts:ro
      - ./.state/data:/app/data
    ports:
      - 10.0.0.1:3001:3001
