services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      NODE_EXTRA_CA_CERTS: /custom-ca/ThawteTLSRSACAG1.crt
    volumes:
      - ./.state/ca:/custom-ca:ro
      - ./.state/data:/app/data
    ports:
      - 10.0.0.1:3001:3001
