version: "3"

tasks:
  default:
    deps: [":vpn:server", custom-cert]
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose up --detach --wait --remove-orphans
    sources:
      - docker-compose.yml
      - .state/ca/*

  custom-cert:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - mkdir -p .state/ca
      - curl 'https://cacerts.digicert.com/ThawteTLSRSACAG1.crt.pem'>.state/ca/ThawteTLSRSACAG1.crt
    status:
      - test -f .state/ca/ThawteTLSRSACAG1.crt
