version: "3"

vars:
  WG_HOME: /etc/wireguard
  WG_PORT: "51820"

  SERVER_WG_INTERFACE_ADDRESS: "10.0.0.1/24"
  HOME_GATEWAY_WG_INTERFACE_ADDRESS: "10.0.0.2/24"

tasks:
  home-gateway:
    deps: [home-gateway-up]

  home-gateway-up:
    deps: [home-gateway-config]
    cmds:
      - systemctl enable wg-quick@wg0
      - systemctl restart wg-quick@wg0
    sources:
      - "{{.WG_HOME}}/wg0.conf"

  home-gateway-config:
    deps: [peer-data-dir, package, keypair, ip-forwarding]
    env:
      WG_PORT: "{{.WG_PORT}}"
      HOME_GATEWAY_WG_INTERFACE_ADDRESS: "{{.HOME_GATEWAY_WG_INTERFACE_ADDRESS}}"
    cmds:
      - cat '{{.TASKFILE_DIR}}/home-gateway-wg0.ini' | HOME_GATEWAY_WG_PRIVATE_KEY="$(cat "{{.WG_HOME}}/iface-keys/private")" SERVER_WG_PUBLIC_KEY="$(cat "{{.WG_HOME}}/peer-data/server.public-key")" SERVER_PUBLIC_IP="$(cat "{{.WG_HOME}}/peer-data/server.public-ip")" envsubst > "{{.WG_HOME}}/wg0.conf"
    preconditions:
      - test -f "{{.WG_HOME}}/peer-data/server.public-key"
      - test -f "{{.WG_HOME}}/peer-data/server.public-ip"
    sources:
      - "{{.TASKFILE_DIR}}/home-gateway-wg0.ini"
      - "{{.WG_HOME}}/iface-keys/private"
      - "{{.WG_HOME}}/peer-data/server.public-key"
      - "{{.WG_HOME}}/peer-data/server.public-ip"

  server:
    deps: [server-up]

  server-up:
    deps: [server-config]
    cmds:
      - systemctl enable wg-quick@wg0
      - systemctl restart wg-quick@wg0
    sources:
      - "{{.WG_HOME}}/wg0.conf"

  server-config:
    deps: [peer-data-dir, package, keypair]
    env:
      WG_PORT: "{{.WG_PORT}}"
      SERVER_WG_INTERFACE_ADDRESS: "{{.SERVER_WG_INTERFACE_ADDRESS}}"
    cmds:
      - cat '{{.TASKFILE_DIR}}/server-wg0.ini' | SERVER_WG_PRIVATE_KEY="$(cat "{{.WG_HOME}}/iface-keys/private")" HOME_GATEWAY_WG_PUBLIC_KEY="$(cat "{{.WG_HOME}}/peer-data/home-gateway.public-key")" CLIENT_WG_PUBLIC_KEY="$(cat "{{.WG_HOME}}/peer-data/client.public-key")" envsubst > "{{.WG_HOME}}/wg0.conf"
    preconditions:
      - test -f "{{.WG_HOME}}/peer-data/home-gateway.public-key"
      - test -f "{{.WG_HOME}}/peer-data/client.public-key"
    sources:
      - "{{.TASKFILE_DIR}}/server-wg0.ini"
      - "{{.WG_HOME}}/iface-keys/private"
      - "{{.WG_HOME}}/peer-data/home-gateway.public-key"
      - "{{.WG_HOME}}/peer-data/client.public-key"

  package:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y wireguard
    status:
      - command -v wg

  keypair:
    deps: [package]
    cmds:
      - bash -c 'umask 077; mkdir -p "{{.WG_HOME}}/iface-keys/"; wg genkey | tee "{{.WG_HOME}}/iface-keys/private" | wg pubkey > "{{.WG_HOME}}/iface-keys/public"'
    status:
      - test -f "{{.WG_HOME}}/iface-keys/private"
      - test -f "{{.WG_HOME}}/iface-keys/public"

  peer-data-dir:
    cmds:
      - mkdir -p "{{.WG_HOME}}/peer-data/"
    status:
      - test -d "{{.WG_HOME}}/peer-data/"

  ip-forwarding:
    cmds:
      - printf "%s\n" "# configured by srkbz/infra" "net.ipv4.ip_forward=1" >>/etc/sysctl.conf
      - sysctl -p
    status:
      - cat /etc/sysctl.conf | grep -E '^net\.ipv4\.ip_forward *= *1$'
      - '[ "$(cat /proc/sys/net/ipv4/ip_forward)" == "1" ]'
