version: "3"

vars:
  WG_HOME: /etc/wireguard
  WG_PORT: "51820"

  SERVER_WG_INTERFACE_ADDRESS: "10.0.0.1/24"

  HOME_GATEWAY_WG_INTERFACE_ADDRESS: "10.0.0.2/24"

tasks:
  home-gateway:
    deps: [package, keypair, ip-forwarding, home-gateway-config]

  home-gateway-config:
    deps: [package, keypair, ip-forwarding]
    env:
      WG_PORT: "{{.WG_PORT}}"
      HOME_GATEWAY_WG_INTERFACE_ADDRESS: "{{.HOME_GATEWAY_WG_INTERFACE_ADDRESS}}"
    cmds:
      - HOME_GATEWAY_WG_PRIVATE_KEY="$(cat "{{.WG_HOME}}/iface-keys/private")" SERVER_WG_PUBLIC_KEY="$(cat "{{.WG_HOME}}/peer-keys/server")" cat '{{.TASKFILE_DIR}}/home-gateway-wg0.ini' | envsubst > "{{.WG_HOME}}/wg0.conf"
    preconditions:
      - test -f "{{.WG_HOME}}/peer-keys/server"

  package:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y wireguard
    status:
      - command -v wg

  keypair:
    deps: [package]
    cmds:
      - bash -c 'umask 077; mkdir -p "{{.WG_HOME}}/iface-keys/"; wg genkey | tee "{{.WG_HOME}}/iface-keys/private" | wg pubkey > "{{.WG_HOME}}/iface-keys/public"'
    status:
      - test -f "{{.WG_HOME}}/iface-keys/private"
      - test -f "{{.WG_HOME}}/iface-keys/public"

  ip-forwarding:
    cmds:
      - printf "%s\n" "# configured by srkbz/infra" "net.ipv4.ip_forward=1" >>/etc/sysctl.conf
      - sysctl -p
    status:
      - cat /etc/sysctl.conf | grep -E '^net\.ipv4\.ip_forward *= *1$'
