version: '3'

vars:
  CADDY_VERSION: '2.8.2'

tasks:
  default:
    deps: [deb]
    cmds:
      - apt-get install -y './.cache/caddy/{{.CADDY_VERSION}}/caddy.deb'
    status:
      - command -v caddy
      - '[[ "$(caddy --version)" == "v{{.CADDY_VERSION}} "* ]]' 

  deb:
    cmds:
      - mkdir -p '.cache/caddy/{{.CADDY_VERSION}}'
      - curl -L -o '.cache/caddy/{{.CADDY_VERSION}}/caddy.deb' 'https://github.com/caddyserver/caddy/releases/download/v{{.CADDY_VERSION}}/caddy_{{.CADDY_VERSION}}_linux_amd64.deb'
    status:
      - '[ -f .cache/caddy/{{.CADDY_VERSION}}/caddy.deb ]'
