version: "3"

vars:
  CADDY_VERSION: "2.8.4"

tasks:
  default:
    deps: [configure]

  configure:
    deps: [install]
    cmds:
      - mkdir -p /etc/caddy/conf.d
      - cp {{.TASKFILE_DIR}}/Caddyfile /etc/caddy/Caddyfile
    sources:
      - "{{.TASKFILE_DIR}}/Caddyfile"
    status:
      - test -d /etc/caddy/conf.d
      - test -f /etc/caddy/Caddyfile

  install:
    deps: [deb]
    cmds:
      - mkdir -p .cache/apt
      - flock .cache/apt/lock apt-get install -y './.cache/caddy/{{.CADDY_VERSION}}/caddy.deb'
    status:
      - command -v caddy
      - '[[ "$(caddy --version)" == "v{{.CADDY_VERSION}} "* ]]'

  deb:
    cmds:
      - mkdir -p '.cache/caddy/{{.CADDY_VERSION}}'
      - curl -L -o '.cache/caddy/{{.CADDY_VERSION}}/caddy.deb' 'https://github.com/caddyserver/caddy/releases/download/v{{.CADDY_VERSION}}/caddy_{{.CADDY_VERSION}}_linux_amd64.deb'
    status:
      - test -f .cache/caddy/{{.CADDY_VERSION}}/caddy.deb

  after-all:
    cmds:
      - systemctl reload caddy
    sources:
      - /etc/caddy/Caddyfile
      - /etc/caddy/conf.d/*
