services:
  freshrss:
    image: freshrss/freshrss
    restart: always
    user: ${USER_ID}:${USER_ID}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      TZ: Europe/Madrid
      CRON_MIN: "15,45"
    volumes:
      - ${FRESHRSS_DATA}:/var/www/FreshRSS/data
    ports:
      - ${HOST}:${PORT}:80
