services:
  freshrss:
    image: freshrss/freshrss
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      TZ: Europe/Madrid
      CRON_MIN: "15,45"
    volumes:
      - ${FRESHRSS_DATA}:/var/www/FreshRSS/data
    ports:
      - ${HOST}:${PORT}:80
      - 10.10.0.1:${PORT}:80
