#!/usr/bin/env bash
set -euo pipefail

TASK_VERSION="3.38.0"

SRKBZ_INFRA_ROOT="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
export SRKBZ_INFRA_ROOT

APPLY_TRIGGER="/srv/srkbz/triggers/APPLY"

function main {
    if [ -f "${APPLY_TRIGGER}" ]; then
        rm "${APPLY_TRIGGER}"
    fi
    ensure-task
    exec "$(task-path)" --dir "nodes/$(hostname)" "$@"
}

function ensure-task {
    if [ ! -f "$(task-path)" ]; then
        sh -c "$(curl --location https://taskfile.dev/install.sh)" \
            -- -d -b "$(dirname "$(task-path)")" "v${TASK_VERSION}"
    fi
}

function task-path {
    printf "%s" "${SRKBZ_INFRA_ROOT}/.cache/task/${TASK_VERSION}/task"
}

main "$@"
