version: "3"

shopt: [globstar]

tasks:
  server:
    deps: [up]

  home-gateway:
    deps: [configure-home-gateway]
    cmds:
      - task: up

  configure-home-gateway:
    deps: [gen]
    cmds:
      - cp /opt/vpn/home-gateway/wg0.conf /etc/wireguard/wg0.conf
    sources:
      - /opt/vpn/home-gateway/wg0.conf
    status:
      - test -f /etc/wireguard/wg0.conf

  up:
    deps: [wireguard, ip-forwarding]
    cmds:
      - chmod 600 /etc/wireguard/wg0.conf
      - systemctl enable wg-quick@wg0
      - systemctl start wg-quick@wg0
      - wg syncconf wg0 <(wg-quick strip wg0)
    sources:
      - /etc/wireguard/wg0.conf
    preconditions:
      - test -f /etc/wireguard/wg0.conf
    status:
      - systemctl status wg-quick@wg0

  reset:
    cmds:
      - wg-quick down wg0 || true
      - systemctl stop wg-quick@wg0

  gen:
    deps: [wireguard, qrencode]
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - ./gen.py
      - cp /opt/vpn/home-gateway/wg0.conf /etc/wireguard/wg0.conf
    sources:
      - gen.py

  wireguard:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y wireguard
    status:
      - command -v wg

  qrencode:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y qrencode
    status:
      - command -v qrencode

  ip-forwarding:
    cmds:
      - printf "%s\n" "# configured by srkbz/infra" "net.ipv4.ip_forward=1" >>/etc/sysctl.conf
      - sysctl -p
    status:
      - cat /etc/sysctl.conf | grep -E '^net\.ipv4\.ip_forward *= *1$'
      - '[ "$(cat /proc/sys/net/ipv4/ip_forward)" == "1" ]'
