version: '3'

tasks:
  default:
    deps: [triggers-dir]
    cmds:
      - cat {{.TASKFILE_DIR}}/srkbz-infra.service | envsubst > /etc/systemd/system/srkbz-infra.service
      - cat {{.TASKFILE_DIR}}/srkbz-infra.path | envsubst > /etc/systemd/system/srkbz-infra.path
      - systemctl daemon-reload
      - systemctl enable srkbz-infra.path
      - systemctl start srkbz-infra.path
    sources:
      - '{{.TASKFILE_DIR}}/srkbz-infra.path'
      - '{{.TASKFILE_DIR}}/srkbz-infra.service'

  triggers:
    deps: [triggers-dir, remove-apply-trigger]

  triggers-dir:
    cmds:
      - mkdir -p /srv/srkbz/triggers
    status:
      - \[ -d /srv/srkbz/triggers ]

  remove-apply-trigger:
    cmds:
      - rm /srv/srkbz/triggers/APPLY
    status:
      - \[ ! -f /srv/srkbz/triggers/APPLY ]
