services:
  freshrss:
    image: freshrss/freshrss
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      TZ: Europe/Madrid
      CRON_MIN: "15,45"
    volumes:
      - ./data:/var/www/FreshRSS/data
    ports:
      - 10.10.0.1:3000:80
