version: "3"

tasks:
  default:
    deps: [build, caddy-config, webhook-config]

  build:
    deps: [workdir, ":docker", target-commit]
    env:
      DOMAIN: "{{.DOMAIN}}"
      REPOSITORY: "{{.REPOSITORY}}"
    cmds:
      - "{{.TASKFILE_DIR}}/build-site.sh"
    status:
      - \[ -f '/srv/srkbz/static-sites/{{.DOMAIN}}/LIVE_COMMIT' ]
      - \[ "$(cat '/srv/srkbz/static-sites/{{.DOMAIN}}/TARGET_COMMIT')" == "$(cat '/srv/srkbz/static-sites/{{.DOMAIN}}/LIVE_COMMIT')" ]

  target-commit:
    deps: [workdir, ":docker"]
    env:
      DOMAIN: "{{.DOMAIN}}"
      REPOSITORY: "{{.REPOSITORY}}"
      BRANCH: "{{.BRANCH}}"
    cmds:
      - "{{.TASKFILE_DIR}}/update-target-commit.sh"
    status:
      - \[ -f '/srv/srkbz/static-sites/{{.DOMAIN}}/TARGET_COMMIT' ]

  caddy-config:
    deps: [":caddy"]
    env:
      DOMAIN: "{{.DOMAIN}}"
    cmds:
      - cat {{.TASKFILE_DIR}}/Caddyfile | envsubst > /etc/caddy/conf.d/{{.DOMAIN}}.caddyfile
      - systemctl reload caddy
    sources:
      - "{{.TASKFILE_DIR}}/Caddyfile"
    status:
      - \[ -f '/etc/caddy/conf.d/{{.DOMAIN}}.caddyfile' ]

  workdir:
    cmds:
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/live
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/builds
    status:
      - "[ -d /srv/srkbz/static-sites/{{.DOMAIN}}/live ]"
      - "[ -d /srv/srkbz/static-sites/{{.DOMAIN}}/build ]"

  webhook-config:
    deps: [":secrets"]
    dotenv:
      - "{{.USER_WORKING_DIR}}/secrets/static-sites/{{.DOMAIN}}.env"
    env:
      DOMAIN: "{{.DOMAIN}}"
      TASKFILE_DIR: "{{.TASKFILE_DIR}}"
      BRANCH: "{{.BRANCH}}"
    cmds:
      - "{{.TASKFILE_DIR}}/webhook-build.py"
    sources:
      - "{{.TASKFILE_DIR}}/webhook-build.py"
      - "{{.USER_WORKING_DIR}}/secrets/static-sites/{{.DOMAIN}}.env"
    status:
      - \[ -f '.cache/webhook/conf/static-site_{{.DOMAIN}}.json' ]
