version: '3'

tasks:
  default:
    deps: [workdir, ':caddy']

  workdir:
    cmds:
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/live
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/builds
    status:
      - '[ -d /srv/srkbz/static-sites/{{.DOMAIN}} ]'
