version: "3"

tasks:
  default:
    deps: [build, caddy-config, webhook-config]

  build:
    deps: [workdir, ":docker", target-commit]
    env:
      DOMAIN: "{{.DOMAIN}}"
      REPOSITORY: "{{.REPOSITORY}}"
    cmds:
      - "{{.TASKFILE_DIR}}/build-site.sh"
    status:
      - \[ -f '/srv/srkbz/static-sites/{{.DOMAIN}}/LIVE_COMMIT' ]
      - \[ "$(cat '/srv/srkbz/static-sites/{{.DOMAIN}}/TARGET_COMMIT')" == "$(cat '/srv/srkbz/static-sites/{{.DOMAIN}}/LIVE_COMMIT')" ]

  target-commit:
    cmds:
      - task: update-target-commit
    status:
      - \[ -f '/srv/srkbz/static-sites/{{.DOMAIN}}/TARGET_COMMIT' ]

  update-target-commit:
    deps: [workdir, ":docker"]
    env:
      DOMAIN: "{{.DOMAIN}}"
      REPOSITORY: "{{.REPOSITORY}}"
      BRANCH: "{{.BRANCH}}"
    cmds:
      - "{{.TASKFILE_DIR}}/update-target-commit.sh"

  caddy-config:
    deps: [":caddy"]
    env:
      DOMAIN: "{{.DOMAIN}}"
    cmds:
      - cat {{.TASKFILE_DIR}}/Caddyfile | envsubst > /etc/caddy/conf.d/{{.DOMAIN}}.caddyfile
      - systemctl reload caddy
    sources:
      - "{{.TASKFILE_DIR}}/Caddyfile"

  workdir:
    cmds:
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/live
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/builds
    status:
      - "[ -d /srv/srkbz/static-sites/{{.DOMAIN}} ]"

  webhook-config:
    dotenv:
      - "{{.USER_WORKING_DIR}}/static-sites/{{.DOMAIN}}.secrets.env"
    env:
      DOMAIN: "{{.DOMAIN}}"
      TASKFILE_DIR: "{{.TASKFILE_DIR}}"
      BRANCH: "{{.BRANCH}}"
    cmds:
      - "{{.TASKFILE_DIR}}/webhook-build.py"
    sources:
      - "{{.TASKFILE_DIR}}/webhook-build.py"
      - "{{.USER_WORKING_DIR}}/static-sites/{{.DOMAIN}}.secrets.env"
