version: '3'

tasks:
  default:
    deps: [workdir, caddy-config]

  build:
    dotenv:
      - static-sites/{{.DOMAIN}}.env
    sources:
      - static-sites/{{.DOMAIN}}.env
    deps: [':docker']
    cmds:
      - '{{.TASKFILE_DIR}}/build-site'

  caddy-config:
    dotenv:
      - static-sites/{{.DOMAIN}}.env
    deps: [':caddy']
    cmds:
      - cat {{.TASKFILE_DIR}}/Caddyfile | envsubst > /etc/caddy/conf.d/{{.DOMAIN}}.caddyfile
      - systemctl reload caddy
    sources:
      - static-sites/{{.DOMAIN}}.env
      - '{{.TASKFILE_DIR}}/Caddyfile'

  workdir:
    cmds:
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/live
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/builds
    status:
      - '[ -d /srv/srkbz/static-sites/{{.DOMAIN}} ]'
