version: '3'

tasks:
  default:
    deps: [build, caddy-config]

  build:
    deps: [workdir, ':docker']
    env:
      DOMAIN: '{{.DOMAIN}}'
      REPOSITORY: '{{.REPOSITORY}}'
      COMMIT: '{{.COMMIT}}'
    cmds:
      - '{{.TASKFILE_DIR}}/build-site.sh'

  caddy-config:
    deps: [':caddy']
    env:
      DOMAIN: '{{.DOMAIN}}'
    cmds:
      - cat {{.TASKFILE_DIR}}/Caddyfile | envsubst > /etc/caddy/conf.d/{{.DOMAIN}}.caddyfile
      - systemctl reload caddy
    sources:
      - '{{.TASKFILE_DIR}}/Caddyfile'

  workdir:
    cmds:
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/live
      - mkdir -p /srv/srkbz/static-sites/{{.DOMAIN}}/builds
    status:
      - '[ -d /srv/srkbz/static-sites/{{.DOMAIN}} ]'
