version: "3"

output: prefixed
run: when_changed

includes:
  minidlna: ./minidlna
  samba: ./samba

tasks:
  default:
    deps: [public-dir, minidlna:configure, samba:configure]

  public-dir:
    cmds:
      - mkdir -p /srv/public
    status:
      - test -d /srv/public
