version: "3"

output: prefixed
run: when_changed

includes:
  minidlna: ./minidlna
  samba: ./samba
  vpn: ../../vpn

tasks:
  default:
    deps: [public-dir, minidlna:configure, samba:configure, vpn:home-gateway]

  public-dir:
    cmds:
      - mkdir -p /srv/public
      - chmod -R 777 /srv/public
    status:
      - test -d /srv/public
