version: '3'

output: prefixed

includes:
  docker: ../../modules/docker
  caddy: ../../modules/caddy
  webhook: ../../modules/webhook
  static-site: ../../modules/static-site

tasks:
  default:
    deps:
      - task: static-site
        vars:
          DOMAIN: sirikon.me
      - task: static-site
        vars:
          DOMAIN: osoondo.com
      - task: static-site
        vars:
          DOMAIN: egin.sirikon.me
      - task: static-site
        vars:
          DOMAIN: astenagusia.eus
      - task: static-site
        vars:
          DOMAIN: 2048.sirikon.me
