version: "3"

output: prefixed
run: when_changed

includes:
  taskw-service: ../../modules/taskw-service
  secrets: ../../modules/secrets
  docker: ../../modules/docker
  caddy: ../../modules/caddy
  webhook: ../../modules/webhook
  freshrss: ../../modules/freshrss
  uptime-kuma: ../../modules/uptime-kuma
  vpn: ../../modules/vpn

tasks:
  default:
    deps:
      - taskw-service
      - secrets
      - webhook
      - freshrss
      - uptime-kuma
      - vpn:server
