version: "3"

tasks:
  default:
    deps: [triggers]
    cmds:
      - cat {{.TASKFILE_DIR}}/srkbz-infra.service | envsubst > /etc/systemd/system/srkbz-infra.service
      - cat {{.TASKFILE_DIR}}/srkbz-infra.path | envsubst > /etc/systemd/system/srkbz-infra.path
      - systemctl daemon-reload
      - systemctl enable srkbz-infra.path
      - systemctl start srkbz-infra.path
    sources:
      - "{{.TASKFILE_DIR}}/srkbz-infra.path"
      - "{{.TASKFILE_DIR}}/srkbz-infra.service"
    status:
      - test -f /etc/systemd/system/srkbz-infra.path
      - test -f /etc/systemd/system/srkbz-infra.service

  triggers:
    deps: [triggers-dir, remove-apply-trigger]

  triggers-dir:
    deps: [triggers-group]
    cmds:
      - mkdir -p /srv/srkbz/triggers
      - chown root:srkbz-infra-triggers /srv/srkbz/triggers
      - chmod --recursive 775 /srv/srkbz/triggers
    status:
      - test -d /srv/srkbz/triggers

  triggers-group:
    cmds:
      - groupadd --force srkbz-infra-triggers
    status:
      - cat /etc/group | grep srkbz-infra-triggers

  remove-apply-trigger:
    cmds:
      - rm -f /srv/srkbz/triggers/APPLY
    status:
      - \[ ! -f /srv/srkbz/triggers/APPLY ]
