version: "3"

tasks:
  default:
    deps: [secrets-download]

  package-unzip:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y unzip
    status:
      - command -v unzip

  package-keepassxc:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y keepassxc
    status:
      - command -v keepassxc-cli

  secrets-download:
    deps: [package-unzip, package-keepassxc]
    dotenv:
      - "{{.USER_WORKING_DIR}}/secrets.env"
    dir: .cache/secrets/download
    cmds:
      - rm -rf *
      - chmod 700 .
      - umask 077 && 'curl -Lo "secrets.zip" "${SECRETS_URL}"'
      - umask 077 && "unzip -o 'secrets.zip' || true"
      - umask 077 && (echo "${SECRETS_PASSWORD}" | keepassxc-cli export --quiet secrets.kdbx > secrets.xml)
    status:
      - \[ -f '{{.USER_WORKING_DIR}}/.cache/secrets/download/secrets.xml' ]
