version: "3"

tasks:
  default:
    deps: [secrets-dir]

  secrets-dir:
    deps: [secrets-xml]
    dir: secrets
    env:
      TASKFILE_DIR: "{{.TASKFILE_DIR}}"
    cmds:
      - "'{{.TASKFILE_DIR}}/secrets-xml-to-dir.sh' '{{.USER_WORKING_DIR}}/.cache/secrets/download/secrets.xml'"
    status:
      - test -d '{{.USER_WORKING_DIR}}/secrets'
    sources:
      - "{{.TASKFILE_DIR}}/secrets-xml-to-dir.sh"
      - "{{.USER_WORKING_DIR}}/.cache/secrets/download/secrets.xml"

  secrets-xml:
    deps: [package-unzip, package-keepassxc]
    dir: .cache/secrets/download
    dotenv:
      - "{{.USER_WORKING_DIR}}/secrets.env"
    cmds:
      - "{{.TASKFILE_DIR}}/secrets-download-extract-export.sh"
    sources:
      - "{{.USER_WORKING_DIR}}/secrets.env"
      - "{{.TASKFILE_DIR}}/secrets-download-extract-export.sh"
    status:
      - test -f '{{.USER_WORKING_DIR}}/.cache/secrets/download/secrets.xml'
    preconditions:
      - . "{{.USER_WORKING_DIR}}/secrets.env" && [ -n "$SECRETS_URL" ]
      - . "{{.USER_WORKING_DIR}}/secrets.env" && [ -n "$SECRETS_PASSWORD" ]

  package-unzip:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y unzip
    status:
      - command -v unzip

  package-keepassxc:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y keepassxc
    status:
      - command -v keepassxc-cli

  clean:
    cmds:
      - rm -rf .cache/secrets
      - rm -rf secrets
