version: "3"

tasks:
  default:
    deps: [secrets-dir]

  package-unzip:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y unzip
    status:
      - command -v unzip

  package-keepassxc:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y keepassxc
    status:
      - command -v keepassxc-cli

  secrets-xml:
    deps: [package-unzip, package-keepassxc]
    dir: .cache/secrets/download
    dotenv:
      - "{{.USER_WORKING_DIR}}/secrets.env"
    cmds:
      - "{{.TASKFILE_DIR}}/secrets-download-extract-export.sh"
    sources:
      - "{{.TASKFILE_DIR}}/secrets-download-extract-export.sh"
      - "{{.USER_WORKING_DIR}}/secrets.env"

  secrets-dir:
    deps: [secrets-xml]
    dir: secrets
    cmds:
      - rm -rf *
      - "'{{.TASKFILE_DIR}}/secrets-xml-to-dir.py' '{{.USER_WORKING_DIR}}/.cache/secrets/download/secrets.xml'"
    sources:
      - "{{.TASKFILE_DIR}}/secrets-xml-to-dir.py"
      - "{{.USER_WORKING_DIR}}/.cache/secrets/download/secrets.xml"

  reset:
    cmds:
      - rm -rf .cache/secrets
      - rm -rf secrets
