version: "3"

tasks:
  default:
    deps: [secrets-xml]

  package-unzip:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y unzip
    status:
      - command -v unzip

  package-keepassxc:
    cmds:
      - mkdir -p .cache/apt/lock
      - flock .cache/apt/lock apt-get install -y keepassxc
    status:
      - command -v keepassxc-cli

  secrets-xml:
    deps: [package-unzip, package-keepassxc]
    dotenv:
      - "{{.USER_WORKING_DIR}}/secrets.env"
    dir: .cache/secrets/zip
    cmds:
      - 'curl -Lo "secrets.zip" "${SECRETS_URL}"'
      - "unzip -o 'secrets.zip'"
      - echo "${SECRETS_PASSWORD}" | keepassxc-cli export --quiet secrets.kdbx > secrets.xml
    sources:
      - "{{.USER_WORKING_DIR}}/secrets.env"
