environment:
  DOCKER_CLEANUP_CRON: '${DOCKER_CLEANUP_CRON:-"0 4 * * 0"}'

tasks:
  default:
    labels:
      discover: "true"
      apt.packages: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    requires: [repository]

  repository:
    required_by: [":apt"]
    script: ./docker-debian-repository.sh
    when:
      check_fails: |
        test -f /etc/apt/keyrings/docker.asc
        test -f /etc/apt/sources.list.d/docker.list

  cleanup:
    labels:
      cron: "${DOCKER_CLEANUP_CRON}"
    script: |
      docker system prune -af
