tasks:
  default:
    labels:
      autorequire: "true"
      apt.packages: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    requires: [repository]

  repository:
    script: ./docker-debian-repository.sh
    when:
      check_fails: |
        test -f /etc/apt/keyrings/docker.asc
        test -f /etc/apt/sources.list.d/docker.list

  cleanup:
    labels:
      cron: "0 4 * * 0"
    script: |
      docker system prune -af
