tasks:
  default:
    requires: [bin]

  bin:
    extends: [":apt:configure"]
    requires: [repository]
    script: cp apt-packages.txt "${APT_PACKAGES_ROOT}/docker.txt"

  repository:
    script: ./docker-debian-repository.sh
    when:
      check_fails: |
        test -f /etc/apt/keyrings/docker.asc
        test -f /etc/apt/sources.list.d/docker.list
