version: '3'

tasks:
  default:
    cmds:
      - '{{.TASKFILE_DIR}}/install-docker-debian.sh'
    status:
      - command -v docker

  cleanup:
    cmds:
      - docker system prune -af
      - docker system df
