version: "3"

tasks:
  configure:
    deps: [package, samba-guest-user]
    cmds:
      - cp '{{.TASKFILE_DIR}}/smb.conf' /etc/samba/smb.conf
      - systemctl restart smbd.service
    sources:
      - "{{.TASKFILE_DIR}}/smb.conf"
    status:
      - test -f /etc/samba/smb.conf

  package:
    cmds:
      - mkdir -p .cache/apt
      - flock .cache/apt/lock apt-get install -y samba
    status:
      - test -f /usr/sbin/smbd

  samba-guest-user:
    cmds:
      - adduser --system samba-guest
    status:
      - cat /etc/passwd | grep samba-guest
