version: "3"

tasks:
  package:
    cmds:
      - mkdir -p .cache/apt
      - flock .cache/apt/lock apt-get install -y samba
    status:
      - test -f /usr/sbin/smbd

  configure:
    deps: [package]
    cmds:
      - cp '{{.TASKFILE_DIR}}/smb.conf' /etc/samba/smb.conf
      - systemctl restart smbd.service
    sources:
      - "{{.TASKFILE_DIR}}/smb.conf"
    status:
      - test -f /etc/samba/smb.conf
