version: "3"

tasks:
  default:
    deps: [triggers]
    cmds:
      - cat {{.TASKFILE_DIR}}/taskw.service | envsubst > /etc/systemd/system/taskw.service
      - cat {{.TASKFILE_DIR}}/taskw.path | envsubst > /etc/systemd/system/taskw.path
      - systemctl daemon-reload
      - systemctl enable taskw.path
      - systemctl start taskw.path
    sources:
      - "{{.TASKFILE_DIR}}/taskw.path"
      - "{{.TASKFILE_DIR}}/taskw.service"
    status:
      - test -f /etc/systemd/system/taskw.path
      - test -f /etc/systemd/system/taskw.service

  triggers-bin:
    cmds:
      - cp "{{.TASKFILE_DIR}}/taskw-triggers" /usr/local/bin/taskw-triggers
    sources:
      - "{{.TASKFILE_DIR}}/taskw-triggers"
    status:
      - test -f /usr/local/bin/taskw-triggers

  triggers:
    deps: [triggers-dir]

  triggers-dir:
    deps: [triggers-group]
    cmds:
      - mkdir -p /opt/taskw/triggers
      - chown root:taskw-triggers /opt/taskw/triggers
      - chmod --recursive 775 /opt/taskw/triggers
    status:
      - test -d /opt/taskw/triggers

  triggers-group:
    cmds:
      - groupadd --force taskw-triggers
    status:
      - cat /etc/group | grep taskw-triggers
