version: "3"

tasks:
  default:
    deps: [triggers]
    cmds:
      - cat {{.TASKFILE_DIR}}/taskw.service | envsubst > /etc/systemd/system/taskw.service
      - cat {{.TASKFILE_DIR}}/taskw.path | envsubst > /etc/systemd/system/taskw.path
      - systemctl daemon-reload
      - systemctl enable taskw.path
      - systemctl start taskw.path
    sources:
      - "{{.TASKFILE_DIR}}/taskw.path"
      - "{{.TASKFILE_DIR}}/taskw.service"
    status:
      - test -f /etc/systemd/system/taskw.path
      - test -f /etc/systemd/system/taskw.service

  triggers:
    deps: [triggers-dir, remove-run-trigger]

  triggers-dir:
    deps: [triggers-group]
    cmds:
      - mkdir -p "${TASKW_ROOT}/.state/taskw/triggers"
      - chown root:taskw-triggers "${TASKW_ROOT}/.state/taskw/triggers"
      - chmod --recursive 775 "${TASKW_ROOT}/.state/taskw/triggers"
    status:
      - test -d "${TASKW_ROOT}/.state/taskw/triggers"

  triggers-group:
    cmds:
      - groupadd --force taskw-triggers
    status:
      - cat /etc/group | grep taskw-triggers

  remove-run-trigger:
    cmds:
      - rm -f "${TASKW_ROOT}/.state/taskw/triggers/RUN"
    status:
      - \[ ! -f "${TASKW_ROOT}/.state/taskw/triggers/RUN" ]
