version: "3"

tasks:
  default:
    deps: [":docker", ":secrets"]
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cat "{{.ROOT_DIR}}/secrets/watchtower.env" | grep "WATCHTOWER_NOTIFICATION_URL=" > .env
      - docker compose up --detach --remove-orphans
    sources:
      - "{{.TASKFILE_DIR}}/docker-compose.yml"
      - "{{.ROOT_DIR}}/secrets/watchtower.env"
    preconditions:
      - . "{{.ROOT_DIR}}/secrets/watchtower.env" && [ -n "$WATCHTOWER_NOTIFICATION_URL" ]
