version: "3"

tasks:
  package:
    cmds:
      - mkdir -p .cache/apt
      - flock .cache/apt/lock apt-get install -y minidlna
    status:
      - test -f /usr/sbin/minidlnad

  configure:
    deps: [package]
    cmds:
      - cp '{{.TASKFILE_DIR}}/minidlna.conf' /etc/minidlna.conf
      - systemctl restart minidlna.service
    sources:
      - "{{.TASKFILE_DIR}}/minidlna.conf"
    status:
      - test -f /etc/minidlna.conf
